### ISSUE TITLE
No Videoplaza?

### ISSUE THREAD

**Issue by emberdart** [jonhoo/html5-video-vast#1]
Hi

Is there anything specific in this library that specifically relates to videoplaza? I've never heard of it and was just looking for a generic vast player. Can I use this for everyone?

Cheers

**Comment by jonhoo** [comment]
This should work fine with any other VAST-based ad provider. Note that it hasn't been updated in a while, and given that I'm no longer working with video players, it is unlikely to be. I do still merge pull requests and such though, so it's not entirely dead. You will probably also want to pull in the latest version of https://github.com/jonhoo/vast-vmap.
